In [15]:
import pandas as pd
import os

In [16]:
os.listdir('data')

['PovStatsData.csv',
 'PovStatsCountry.csv',
 'poverty.csv',
 'PovStatsSeries.csv',
 'lat_long.csv',
 'PovStatsCountry-Series.csv',
 'PovStatsFootNote.csv']

In [17]:
df = pd.read_csv('data/PovStatsData.csv')

In [18]:
df

,Country Name,Country Code,Indicator Name,Indicator Code,1974,1975,1976,1977,1978,1979,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 50
0,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PC40.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT10.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT60.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PCAP.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.POV.XPND.MD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11835,Zimbabwe,ZWE,"Survey mean consumption or income per capita, ...",SI.SPR.PCAP,NaN,NaN,NaN,NaN,NaN,NaN,...,4.85,NaN,NaN,NaN,NaN,NaN,3.91,NaN,NaN,NaN
11836,Zimbabwe,ZWE,Urban poverty gap at national poverty lines (%),SI.POV.URGP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11837,Zimbabwe,ZWE,Urban poverty gap at national poverty lines (%...,SI.POV.URGP.NC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11838,Zimbabwe,ZWE,Urban poverty headcount ratio at national pove...,SI.POV.URHC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11839,Zimbabwe,ZWE,Urban poverty headcount ratio at national pove...,SI.POV.URHC.NC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', 'Unnamed: 50'],
      dtype='object')

In [21]:
df.columns = df.columns.str.strip()

In [22]:
#filter the data first

In [23]:
filtered_df = df[df['Indicator Name'] == 'GINI index (World Bank estimate)']

In [ ]:
fi