In [3]:
import pandas as pd

In [8]:
# Read the CSV file into a DataFrame
df1 = pd.read_csv('povertydata.csv')

/tmp/ipykernel_40861/4052457806.py:2: DtypeWarning: Columns (66,67,73,79,82,83,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('povertydata.csv')

In [9]:
df1

,Country Name,Country Code,year,"Annualized growth in per capita real survey mean consumption or income, bottom 40% (%)","Annualized growth in per capita real survey mean consumption or income, top 10% (%)","Annualized growth in per capita real survey mean consumption or income, top 60% (%)","Annualized growth in per capita real survey mean consumption or income, total population (%)",Annualized growth in per capita real survey median income or consumption expenditure (%),GINI index (World Bank estimate),Growth component of change in poverty at $1.90 a day (2011 PPP) (% of change),...,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30,is_country
0,Afghanistan,AFG,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN,True
1,Afghanistan,AFG,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN,True
2,Afghanistan,AFG,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN,True
3,Afghanistan,AFG,1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN,True
4,Afghanistan,AFG,1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8282,Zimbabwe,ZWE,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN,True
8283,Zimbabwe,ZWE,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN,True
8284,Zimbabwe,ZWE,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN,True
8285,Zimbabwe,ZWE,2017,-3.75,-3.04,-3.45,-3.5,-4.54,44.3,NaN,...,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN,True
8286,Zimbabwe,ZWE,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN,True

In [10]:
df1.columns

Index(['Country Name', 'Country Code', 'year',
       'Annualized growth in per capita real survey mean consumption or income, bottom 40% (%)',
       'Annualized growth in per capita real survey mean consumption or income, top 10% (%)',
       'Annualized growth in per capita real survey mean consumption or income, top 60% (%)',
       'Annualized growth in per capita real survey mean consumption or income, total population (%)',
       'Annualized growth in per capita real survey median income or consumption expenditure (%)',
       'GINI index (World Bank estimate)',
       'Growth component of change in poverty at $1.90 a day (2011 PPP) (% of change)',
       'Growth component of change in poverty at $3.20 a day (2011 PPP) (% of change)',
       'Growth component of change in poverty at $5.50 a day (2011 PPP) (% of change)',
       'Income share held by fourth 20%', 'Income share held by highest 10%',
       'Income share held by highest 20%', 'Income share held by lowest 10%',
       'Income share held by lowest 20%', 'Income share held by second 20%',
       'Income share held by third 20%',
       'Median daily per capita income or consumption expenditure (2011 PPP)',
       'Multidimensional poverty, Drinking water (% of population deprived)',
       'Multidimensional poverty, Educational attainment (% of population deprived)',
       'Multidimensional poverty, Educational enrollment (% of population deprived)',
       'Multidimensional poverty, Electricity (% of population deprived)',
       'Multidimensional poverty, Headcount ratio (% of population)',
       'Multidimensional poverty, Monetary poverty (% of population deprived)',
       'Multidimensional poverty, Sanitation (% of population deprived)',
       'Number of poor at $1.90 a day (2011 PPP) (millions)',
       'Number of poor at $3.20 a day (2011 PPP) (millions)',
       'Number of poor at $5.50 a day (2011 PPP) (millions)',
       'Population, total', 'Poverty gap at $1.90 a day (2011 PPP) (%)',
       'Poverty gap at $3.20 a day (2011 PPP) (% of population)',
       'Poverty gap at $5.50 a day (2011 PPP) (% of population)',
       'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)',
       'Poverty headcount ratio at $1.90 a day, Female (2011 PPP) (% of female population)',
       'Poverty headcount ratio at $1.90 a day, Male  (2011 PPP) (% of male population)',
       'Poverty headcount ratio at $1.90 a day, age 0-14  (2011 PPP) (% of population age 0-14)',
       'Poverty headcount ratio at $1.90 a day, age 15-64 (2011 PPP) (% of population age 15-64)',
       'Poverty headcount ratio at $1.90 a day, age 65+ (2011 PPP) (% of population age 65+)',
       'Poverty headcount ratio at $1.90 a day, rural (2011 PPP) (% of rural population)',
       'Poverty headcount ratio at $1.90 a day, urban (2011 PPP) (% of urban population)',
       'Poverty headcount ratio at $1.90 a day, with primary education (2011 PPP) (% of population age 16+ with primary education)',
       'Poverty headcount ratio at $1.90 a day, with secondary education (2011 PPP) (% of population age 16+ with secondary education)',
       'Poverty headcount ratio at $1.90 a day, without education (2011 PPP) (% of population age 16+ without education)',
       'Poverty headcount ratio at $1.90 a day,  with Tertiary/post-secondary education (2011 PPP) (% of population age 16+ with Tertiary/post-secondary education)',
       'Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)',
       'Poverty headcount ratio at $5.50 a day (2011 PPP) (% of population)',
       'Poverty headcount ratio at national poverty lines (% of population)',
       'Poverty headcount ratio at national poverty lines (% of population), including noncomparable values',
       'Redistribution component of change in poverty at $1.90 a day (2011 PPP) (% of change)',
       'Redistribution component of change in poverty at $3.20 a day (2011 PPP) (% of change)',
       'Redistribution component of change in poverty at $5.50 a day (2011 PPP) (% of change)',
       'Survey mean consumption or income per capita, bottom 40% (2011 PPP $ per day)',
       'Survey mean consumption or income per capita, top 10% (2011 PPP $ per day)',
       'Survey mean consumption or income per capita, top 60% (2011 PPP $ per day)',
       'Survey mean consumption or income per capita, total population (2011 PPP $ per day)',
       'Short Name', 'Table Name', 'Long Name', '2-alpha code',
       'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code',
       'National accounts base year', 'National accounts reference year',
       'SNA price valuation', 'Lending category', 'Other groups',
       'System of National Accounts', 'Alternative conversion factor',
       'PPP survey year', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Latest population census', 'Latest household survey',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data', 'Unnamed: 30',
       'is_country'],
      dtype='object')

In [11]:
df_revamped =df1[['Income share held by fourth 20%','Income share held by highest 20%','Income share held by lowest 20%','Income share held by third 20%','Income share held by highest 10%','Income share held by lowest 10%','Income share held by second 20%']]

In [13]:
df_revamped

,Income share held by fourth 20%,Income share held by highest 20%,Income share held by lowest 20%,Income share held by third 20%,Income share held by highest 10%,Income share held by lowest 10%,Income share held by second 20%
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
8282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8283,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8285,20.6,51.1,6.0,13.2,34.8,2.5,9.1
8286,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Strip leading and trailing whitespaces from column names
df.columns = df.columns.str.strip()

# Select only the desired columns
df = df[['Country Name', 'year', 'GINI index (World Bank estimate)']]

# Drop rows with NaN values in the 'GINI index (World Bank estimate)' column
df = df.dropna(subset=['GINI index (World Bank estimate)'])

# Sort the DataFrame by the 'year' column
df = df.sort_values(by='year')

In [6]:
df

         Country Name  year  GINI index (World Bank estimate)
7718   United Kingdom  1974                              30.0
7763    United States  1974                              35.3
6999           Sweden  1975                              24.3
1126           Canada  1975                              33.3
2474           France  1978                              35.2
...               ...   ...                               ...
2649          Georgia  2018                              36.4
8077          Vietnam  2018                              35.7
179            Angola  2018                              51.3
3998  Kyrgyz Republic  2018                              27.7
3368        Indonesia  2018                              39.0

[1674 rows x 3 columns]